import { NextAuthProvider } from './AuthProvider';
import NavMenu from './NavMenu';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <NextAuthProvider>
            <html lang="en">
                <body>
                    <nav>
                        <NavMenu></NavMenu>
                    </nav>
                    {children}
                </body>
            </html>
        </NextAuthProvider>
    );
}
